[versions]
kotlin = "2.2.20"
gdx = "1.13.5"
gdx-box2d = "3.1.1-0"
ktx = "1.13.1-rc1"
protobuf = "4.32.1"
vis = "1.5.7"
caffeine = "3.2.2"
uuid = "5.1.1"
oshaiLogging = "7.0.13"
log4j = "2.25.2"
junit = "5.13.4"
mockk = "1.14.6"
jansi = "2.4.2"
fastutil = "8.5.18"
netty = "4.2.6.Final"
kotlinCoroutines = "1.10.2"

stacktracedecoroutinator = "2.5.7"
spotless = "7.2.1"
versionsPlugin = "0.52.0"
protobufPlugin = "0.9.5"

[libraries]
gdx-core = { group = "com.badlogicgames.gdx", name = "gdx", version.ref = "gdx" }
gdx-freetype = { group = "com.badlogicgames.gdx", name = "gdx-freetype", version.ref = "gdx" }
gdx-backend-headless = { group = "com.badlogicgames.gdx", name = "gdx-backend-headless", version.ref = "gdx" }
gdx-backend-lwjgl3 = { group = "com.badlogicgames.gdx", name = "gdx-backend-lwjgl3", version.ref = "gdx" }
gdx-freetype-platform = { group = "com.badlogicgames.gdx", name = "gdx-freetype-platform", version.ref = "gdx" }
gdx-platform = { group = "com.badlogicgames.gdx", name = "gdx-platform", version.ref = "gdx" }

gdx-box2d = { group = "com.badlogicgames.gdx", name = "gdx-box2d", version.ref = "gdx-box2d" }
gdx-box2d-utils = { group = "com.badlogicgames.gdx", name = "gdx-box2d-utils", version.ref = "gdx-box2d" }
gdx-box2d-platform = { group = "com.badlogicgames.gdx", name = "gdx-box2d-platform", version.ref = "gdx-box2d" }

ktx-actors = { group = "io.github.libktx", name = "ktx-actors", version.ref = "ktx" }
ktx-app = { group = "io.github.libktx", name = "ktx-app", version.ref = "ktx" }
ktx-assets = { group = "io.github.libktx", name = "ktx-assets", version.ref = "ktx" }
ktx-async = { group = "io.github.libktx", name = "ktx-async", version.ref = "ktx" }
ktx-collections = { group = "io.github.libktx", name = "ktx-collections", version.ref = "ktx" }
ktx-graphics = { group = "io.github.libktx", name = "ktx-graphics", version.ref = "ktx" }
ktx-style = { group = "io.github.libktx", name = "ktx-style", version.ref = "ktx" }
ktx-vis = { group = "io.github.libktx", name = "ktx-vis", version.ref = "ktx" }
ktx-vis-style = { group = "io.github.libktx", name = "ktx-vis-style", version.ref = "ktx" }
ktx-ashley = { group = "io.github.libktx", name = "ktx-ashley", version.ref = "ktx" }
ktx-box2d = { group = "io.github.libktx", name = "ktx-box2d", version.ref = "ktx" }
ktx-math = { group = "io.github.libktx", name = "ktx-math", version.ref = "ktx" }
ktx-preferences = { group = "io.github.libktx", name = "ktx-preferences", version.ref = "ktx" }
ktx-log = { group = "io.github.libktx", name = "ktx-log", version.ref = "ktx" }

log4j-bom = { group = "org.apache.logging.log4j", name = "log4j-bom", version.ref = "log4j" }
log4j-api = { group = "org.apache.logging.log4j", name = "log4j-api", version.ref = "log4j" }
log4j-core = { group = "org.apache.logging.log4j", name = "log4j-core", version.ref = "log4j" }
log4j-slf4j = { group = "org.apache.logging.log4j", name = "log4j-slf4j2-impl", version.ref = "log4j" }

protobuf-bom = { group = "com.google.protobuf", name = "protobuf-bom", version.ref = "protobuf" }
protobuf-kotlin = { group = "com.google.protobuf", name = "protobuf-kotlin", version.ref = "protobuf" }
protobuf-protoc = { group = "com.google.protobuf", name = "protoc", version.ref = "protobuf" }

kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }
kotlin-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }
kotlin-bom = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-bom", version.ref = "kotlinCoroutines" }

apacheCommons-collections = { group = "org.apache.commons", name = "commons-collections4", version = "4.5.0" }
apacheCommons-lang = { group = "org.apache.commons", name = "commons-lang3", version = "3.19.0" }

caffeine = { group = "com.github.ben-manes.caffeine", name = "caffeine", version.ref = "caffeine" }
uuid = { group = "com.fasterxml.uuid", name = "java-uuid-generator", version.ref = "uuid" }
visUi = { group = "com.kotcrab.vis", name = "vis-ui", version.ref = "vis" }
inGameConsole = { group = "com.strongjoshua", name = "libgdx-inGameConsole", version = "1.0.0" }
netty-bom = { group = "io.netty", name = "netty-bom", version.ref = "netty" }
netty-all = { group = "io.netty", name = "netty-all", version.ref = "netty" }
annotations = { group = "org.jetbrains", name = "annotations", version = "26.0.2-1" }
oshaiLogging = { group = "io.github.oshai", name = "kotlin-logging-jvm", version.ref = "oshaiLogging" }
fastutil = { group = "it.unimi.dsi", name = "fastutil", version.ref = "fastutil" }
jansi = { group = "org.fusesource.jansi", name = "jansi", version.ref = "jansi" } # deprecated, replace with https://github.com/jline/jline3
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }

junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }
junit-vintage-engine = { group = "org.junit.vintage", name = "junit-vintage-engine", version.ref = "junit" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-allopen = { id = "org.jetbrains.kotlin.plugin.allopen", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versionsPlugin" }
protobuf = { id = "com.google.protobuf", version.ref = "protobufPlugin" }
stacktracedecoroutinator = { id = "dev.reformator.stacktracedecoroutinator", version.ref = "stacktracedecoroutinator" }
